#!/bin/bash

sed '/<!DOCTYPE/,/Adopt<\/td>/d' | sed '/<tr>/,/<\/td>/d' | tr '[:upper:]' '[:lower:]' | sed 's/<u>//g' | sed 's/<\/u>//g' | sed s/\`/\'/g | sed 's/, /\n/g' | sed 's/ /\n/g' | sed 's/<[^>]*>//g' | sed '/www\./,/letter\./d' | sed 's/^\s*//g' | sed '/^$/d' | sed 's/*\s$//g' | grep -v "[^pk'mnwlhaeiou]" | sort -u 
